### ISSUE TITLE
Not getting last field

### ISSUE THREAD

**Issue by kyclark** [tony-o/perl6-csv-parser#12]
I'm finding that this module fails to get the last field in my data, e.g.:

    $ cat test.pl6
    #!/usr/bin/env perl6

    use CSV::Parser;
    use Data::Dump;

    my $fh     = open 'test.csv', :r;
    my $parser = CSV::Parser.new( file_handle => $fh, contains_header_row => True );
    my %data   = %($parser.get_line());
    say "data = ", Dump(%data);
    $ cat test.csv
    name,rank,serial_num
    Ken,Private,1656401
    $ ./test.pl6
    data = {
      name => "Ken".Str,
      rank => "Private".Str,
    }
    $ cat test.csv
    name,rank,serial_num,age
    Ken,Private,1656401,43
    $ ./test.pl6
    data = {
      name       => "Ken".Str,
      rank       => "Private".Str,
      serial_num => "1656401".Str,
    }

**Comment by tony-o** [comment]
Is this happening intermittently or am I reading that output wrong?



On Wed, Jan 27, 2016 at 8:02 AM -0800, "Ken Youens-Clark" <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm finding that this module fails to get the last field in my data, e.g.:

$ cat test.pl6
#!/usr/bin/env perl6

use CSV::Parser;
use Data::Dump;

my $fh     = open 'test.csv', :r;
my $parser = CSV::Parser.new( file_handle => $fh, contains_header_row => True );
my %data   = %($parser.get_line());
say "data = ", Dump(%data);
$ cat test.csv
name,rank,serial_num
Ken,Private,1656401
$ ./test.pl6
data = {
  name => "Ken".Str,
  rank => "Private".Str,
}
$ cat test.csv
name,rank,serial_num,age
Ken,Private,1656401,43
$ ./test.pl6
data = {
  name       => "Ken".Str,
  rank       => "Private".Str,
  serial_num => "1656401".Str,
}


-

**Comment by tony-o** [comment]
Sorry, missed that you added a field on the second go.  I’ll take a look

**Comment by tony-o** [comment]
@kyclark please re-install the module, that issue should be resolved with #13

**Comment by kyclark** [comment]
All good now.  Thanks!
