### ISSUE TITLE
Error when hit EOF

### ISSUE THREAD

**Issue by fil512** [tony-o/perl6-csv-parser#6]
An example of how to iterate through all lines in a file would be helpful.  I tried the following, but I get an error:

     while ($next_line = $parser.get_line()) {
          %line = %$next_line;

Here's the error I get:

Type check failed for return value; expected 'Hash' but got 'Any'
  in any return_error at src/vm/moar/Perl6/Ops.nqp:649
  in method get_line at lib\CSV\Parser.pm:51
  in block <unit> at C:\Users\Ken\dev\perl\kentest.p6:16

**Comment by fil512** [comment]
For now I got it to work by doing this:

while (!$fh.eof) {
  %line = %($parser.get_line());

**Comment by tony-o** [comment]
@fil512 can you try it again (reinstall the module)?  there was a commit that introduced that bug and your original syntax should work.  I was able to reproduce the problem and then resolve it -

**Comment by fil512** [comment]
fixed.  thanks
